import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
    vi: {
        nav_1: 'VỀ MGREEN',
        nav_2: 'NHÀ TÀI TRỢ',
        nav_3: 'ĐĂNG NHẬP / ĐĂNG KÍ',
        nav_4: 'DỰ ÁN',
        nav_5: 'TIN TỨC',
        nav_6: 'LIÊN HỆ',
        nav_7: 'DOWNLOAD APP',
        nav_8: 'TIẾNG VIỆT',
        nav_9: 'ENGLISH',
        nav_10:'ĐĂNG NHẬP',
        nav_11:'ĐĂNG KÍ',
        slide_1:'tòa nhà thông minh',
        slide_2:'cư dân thông thái',
        slide_3:'phân loại rác tái chế và tích điểm',
        slide_4:'để nhận hàng ngàn ưu đãi và quà tặng',
        slide_5:'đăng kí miễn phí thẻ mgreen',
        slide_6:'nhận ngay thẻ ưu đãi mgreen trị giá hàng triệu đồng',
        slide_7:'thu gom rác như uber',
        slide_8:'Phân loại,thu gom rác tái chế và quà tặng đổi điểm cho cư dân qua app Mpoint',
        slide_9:'công nghệ smart city',
        slide_10:'Dự án ứng dụng công nghệ Smart city phục vụ việc phân loại các loại rác.',
        introduce:'giới thiệu',
        introduce_1:'MGreen là dự án xã hội, phi lợi nhuận, nhằm xây dựng thói quen văn minh trong phân loại rác tại gia đình và bảo vệ môi trường',
        introduce_2:'Dự án được sự chỉ đạo của UBND TP Hà Nội và là một trong ba dự án khởi nghiệp xuất sắc được Sở Thông tin truyền thông Hà Nội trao bằng khen',
        introduce_3:'Cư dân tại các tòa nhà triển khai dự án được cung cấp MIỄN PHÍ 1 sọt đựng rác tái chế và  1 Thẻ tích điểm cùng ứng dụng gọi người thu gom. Các hộ gia đình thực hiện việc phân loại rác, sử dụng ứng dụng để gọi người thu gom và được tích điểm thưởng. Điểm thưởng có thể đổi được nhiều phần quà có giá trị...',
        introduce_4:'HÃY CHUNG TAY VÌ THÀNH PHỐ HÀ NỘI THÔNG MINH XANH, SẠCH, ĐẸP',
        introduce_5:'HÃY CHUNG TAY VÌ THÀNH PHỐ HÀ NỘI THÔNG MINH XANH, SẠCH, ĐẸP',
        classify_1:'Phân loại rác tái chế',
        classify_2:'Phân loại và thu gom rác tái chế',
        classify_3:'Thẻ mGreen',
        classify_4:'Thẻ mGreen được dùng để tích điểm',
        classify_5:'Ưu đãi, quà tặng',
        classify_6:'Người dùng được tích điểm, tặng quà',
        classify_7:'Tặng sọt đựng rác tái chế & thẻ mgreen',
        classify_8:'App thông báo thu gom dễ dàng tiện lợi',
        classify_9:'Người dùng được tích điểm, tặng quà',
        footer_1:'Dự án Smart City - mGreen',
        footer_2:'614  Lạc Long Quân - Tây Hồ - Hà Nội',
        footer_3:'0934 68 66 21',
        footer_4:'thoatran@mgreen.vn',
        footer_5:'Chat cùng mGreen',
        introduceatm:'Hướng dẫn cài thẻ mGeen',
        componenttab_1:'DownLoad App mGreen từ AppStore/CH Play',
        componenttab_2:'Gọi thu gom',
        componenttab_3:'Xác nhận thu gom',
        componenttab_4:'Tích điểm, đổi quà, nhận ưu đãi',
        mgreen_1:'Sứ mệnh',
        mgreen_2:'Doanh nghiệp xã hội uy tín , tin cậy góp phần xây thói quen phân loai rác  và tích điểm, tặng quà cho cư dân trên toàn quốc. Vì văn hoá Việt Nam tốt hơn, Vì môi trường thông minh , xanh- sạch- đẹp.',
        mgreen_3:'Tầm nhìn',
        mgreen_4:'Doanh nghiệp xã hội mGreen là cầu nối của cư dân và đối tác ưu đãi để phân loại rác là hành động, thói quen thường lệ trên toàn Việt Nam',
        mgreen_5:'Giá trị cốt lõi',
        mgreen_6:'Nhiệt huyết Vì cộng đồng – Trung thực-  Chuyên nghiệp – Uy tín- Hiệu quả- Tinh thần đội nhómHướng dẫn cài thẻ tích điểm phân loại rác mGreen',
    },
    en: {
        nav_1: 'ABOUT MGREEN',
        nav_2: 'SPONSOR',
        nav_3: 'LOGIN/SIGNIN',
        nav_4: 'PROJECT',
        nav_5: 'NEW',
        nav_6: 'CONTACT',
        nav_7: 'DOWNLOAD APP',
        nav_8: 'VIETNAMESE',
        nav_9: 'ENGLISH',
        nav_10:'LOGIN',
        nav_11:'SIGNIN',
        slide_1:'SMART HOUSE',
        slide_2:'WISE PEOPLE',
        slide_3:'Point accumulation,',
        slide_4:'sorting waste mgreen',
        slide_5:'FREE REGISTRATION FOR MEMBER CARDS',
        slide_6:'Get discounted million mgreen card',
        slide_7:'COLLECTION AS UBER',
        slide_8:'Classify, recycle, and gift points to residents via the Mpoint app',
        slide_9:'SMART CITY TECHNOLOGY',
        slide_10:'Smart city technology application for sorting garbage.',
        introduce:'INTRODUCE',
        introduce_1:'MGreen is a social, non-profit project that aims to build a civilized habit of sorting household waste and protecting the environment.',
        introduce_2:'The project was directed by the Hanoi People’s Committee and is one of three excellent start-up projects awarded by the Hanoi Information and Communication Department.',
        introduce_3:'Residents of the project buildings are provided FREE 1 recycling bin and 1 collector card with application to collect collectors. Households classify rubbish, use the application to collect collectors and earn bonus points. Rewards can be exchanged for many valuable gifts.',
        introduce_4:'HERE FOR GREEN HANOI CITY, CLEAN, BEAUTIFUL',
        introduce_5:'HERE FOR GREEN HANOI CITY, CLEAN, BEAUTIFUL',
        classify_1:'Classification of recyclable waste',
        classify_2:'Classify and collect garbage',
        classify_3:'MGreen card',
        classify_4:'MGreen card is used to accumulate points',
        classify_5:'Incentives, gifts',
        classify_6:'Users accumulate points, give gifts',
        classify_7:'Give away recyclable trash & mgreen card',
        classify_8:'App notifications are easy to collect',
        classify_9:'Encouraged: accumulate points, give gifts',
        footer_1:'Smart City project - mGreen',
        footer_2:'614  Lạc Long Quân - Tây Hồ - Hà Nội',
        footer_3:'0934 68 66 21',
        footer_4:'thoatran@mgreen.vn',
        footer_5:'Chat with mGreen',
        introduceatm:'How to install mGeen card',
        componenttab_1:'DownLoad App mGreen from AppStore / CH Play',
        componenttab_2:'Call collectors',
        componenttab_3:'Confirmation of collection',
        componenttab_4:'Earn points, redeem, receive incentives',
        mgreen_1:'Mission',
        mgreen_2:'Reliable and reliable social enterprise contributes to the habit of distributing rubbish and collecting points, giving gifts to residents across the country. Because Vietnamese culture is better, because the environment is smart, green – clean – beautiful.',
        mgreen_3:'Vision',
        mgreen_4:'MGreen social enterprise is a bridge between residents and partners to classify rubbish is the habit, routine routine throughout Vietnam',
        mgreen_5:'Core values',
        mgreen_6:'For the community - Honesty- Professional - Prestige - Effectiveness - Team spiritGallery Guide to mark the garbage mGreen',
    }
});

export default strings;