import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
    vi: {
        nav_1: 'VỀ MGREEN',
        cooperate: 'Đồng hành',
        nav_2: 'NHÀ TÀI TRỢ',
        nav_3: 'ĐĂNG NHẬP',
        nav_4: 'ƯU ĐÃI',
        nav_5: 'TIN TỨC',
        change: 'Thay đổi số điện thoại',
        nav_6: 'PHẢN HỒI',
        nav_7: 'DOWNLOAD APP MGREEN',
        nav_8: 'TIẾNG VIỆT',
        nav_9: 'ENGLISH',
        nav_10: 'ĐĂNG NHẬP',
        nav_11: 'ĐĂNG KÍ',
        nav_12: 'CÁC ĐỐI TÁC',
        nav_13: 'ĐỘI NGŨ TÌNH NGUYỆN VIÊN',
        nav_14: 'Nhân viên thu gom',
        nav_15: 'hướng dẫn Phân loại rác',
        textPLR: 'Xã hội ngày càng phát triển, cuộc sống của con người ngày càng đầy đủ và hiện đại, nhưng đi kèm với đó là hệ luỵ ô nhiễm môi trường cũng ngày càng nghiêm trọng. Mặc dù trên cả nước cũng có nhiều nhà máy chuyên tái chế phế liệu, chuyên xử lý rác thải đã hoạt động rất hiệu quả nhưng vẫn không làm giảm được tình trạng này. Và phần lớn là do nguồn rác thải chưa được phân loại đúng cách. Vậy như thế nào được gọi là phân loại đúng cách ?.Trước khi được đưa đi xử lý thì tất cả các loại rác thải nói chung cần được phân loại theo đúng yêu cầu. Đó là loại tái chế và không tái chế. Những loại không tái chế bao gồm các loại rác hữu cơ dễ phân hủy như : thức ăn thừa, hoặc rau củ quả hỏng, vỏ trái cây…Và khi được tổng hợp lại sẽ được đưa về nhà máy và làm phân bón. Còn loại tái chế là những loại vật dụng được loại ra trong quá trình sản xuất hoặc quá trình sử dụng, nó bao gồm các loại giấy, nhựa, sắt, thép, túi nilon khô sạch  … Tùy vào đặc tính của mỗi loại thì chúng sẽ được phân loại riêng biệt và đưa vào tái chế với nhiều mục đích khác nhau sao cho phù hợp nhất có thể.Quá trình phân loại rác thải giúp giảm được lượng rác thải ở trong cộng đồng thải ra ngoài môi trường cũng như tiết kiệm được rất nhiều chi phí để thu gom, vận chuyển và xử lý. Hiện tại, ở giai đoạn 2018 , dự án mGreen chỉ thu những loại rác có thể tái chế được như : giấy , nhựa , kim loại , túi nilon khô và sạch , pin . Đặc biệt , khi cư dân có pin thì nên bỏ vào 1 túi nilon khô sạch hoặc một chai nhựa khô sạch và để tránh xa tầm tay trẻ em .',
        nav_16: 'Địa điểm thu mua và tái chế',
        nav_17: 'Lực lượng thu gom Mgreen',
        nav_18: 'Quy trình thu gom',
        nav_19: 'Sự ra đời mGreen',
        nav_20: 'kế hoạch triển khai',
        nav_21: 'SỨ MỆNH - TẦM NHÌN',
        nav_22: 'GIÁ TRỊ CỐT LÕI',
        slide_1: 'tòa nhà thông minh',
        slide_2: 'cư dân thông thái',
        slide_3: 'Phân loại rác tái chế và tích điểm',
        slide_4: 'Để nhận hàng ngàn ưu đãi và quà tặng',
        slide_5: 'đăng kí miễn phí thẻ mgreen',
        slide_6: 'nhận ngay thẻ ưu đãi mgreen trị giá hàng triệu đồng',
        slide_7: 'thu gom rác bằng SMARTPHONE',
        slide_8: 'Ứng dụng tích hợp tính năng gọi thu gom rác tái chế và tích điểm , tặng quà khi phân loại rác tại nguồn',
        slide_9: 'công nghệ smart city',
        slide_10: 'Dự án ứng dụng công nghệ Smart city phục vụ việc phân loại rác.',
        introduce: 'giới thiệu',
        loginFacebook: 'Đăng Nhập Với Facebook',
        loginGoogle: 'Đăng Nhập với Google',
        introduce_1: 'MGreen là dự án xã hội, phi lợi nhuận, nhằm xây dựng thói quen văn minh trong phân loại rác tại gia đình và bảo vệ môi trường',
        introduce_2: 'Dự án được sự chỉ đạo của UBND TP Hà Nội và là một trong ba dự án khởi nghiệp xuất sắc được Sở Thông tin truyền thông Hà Nội trao bằng khen',
        introduce_3: 'Cư dân tại các tòa nhà triển khai dự án được cung cấp MIỄN PHÍ 1 sọt đựng rác tái chế và  1 Thẻ tích điểm cùng ứng dụng gọi người thu gom. Các hộ gia đình thực hiện việc phân loại rác, sử dụng ứng dụng để gọi người thu gom và được tích điểm thưởng. Điểm thưởng có thể đổi được nhiều phần quà có giá trị...',
        introduce_4: 'HÃY CHUNG TAY VÌ THÀNH PHỐ HÀ NỘI THÔNG MINH XANH, SẠCH, ĐẸP',
        introduce_5: 'CHUNG TAY XÂY DỰNG THÀNH PHỐ CỦA BẠN THÔNG MINH HƠN VÀ XANH – SẠCH – ĐẸP HƠN',
        introduce_6: 'TẢI ỨNG DỤNG MGREEN',
        introduce_7: 'TÌM HIỂU THÊM',
        classify_1: 'Tặng đồ đựng rác',
        classify_2: 'Người dùng sẽ được tặng 1 sọt rác/túi sinh học để đựng rác tái chế',
        classify_3: 'Tặng thẻ mGreen',
        classify_4: 'Người dùng sẽ được tặng thẻ mGreen miễn phí, đồng thời cũng được cài đặt miễn phí ứng dụng mGreen trên mobile. Thẻ/ứng dụng mGreen sẽ tích lũy điểm thưởng sau mỗi lần thu gom rác',
        classify_5: 'Hưởng các ưu đãi',
        classify_6: 'Người dùng được đổi điểm thưởng đã tích lũy lấy phiếu quà tặng hoặc phiếu tích tem từ các đơn vị đối tác liên kết với mGreen',
        classify_7: 'Tặng sọt đựng rác tái chế & thẻ mgreen',
        classify_8: 'App thông báo thu gom dễ dàng tiện lợi',
        classify_9: 'Người dùng được tích điểm, tặng quà',
        footer_1: 'Dự án Smart City - mGreen',
        footer_2: '614  Lạc Long Quân - Tây Hồ - Hà Nội',
        footer_3: '0934 68 66 21',
        footer_4: 'thoatran@mgreen.vn',
        footer_5: 'Chat cùng mGreen',
        introduceatm: 'Hướng dẫn cài thẻ mGeen',
        componenttab_1: 'DownLoad App mGreen từ AppStore/CH Play',
        componenttab_2: 'Gọi thu gom',
        componenttab_3: 'Xác nhận thu gom',
        componenttab_4: 'Tích điểm, đổi quà, nhận ưu đãi',
        mgreen_1: 'Sứ mệnh',
        close: 'Đóng',
        OkBox: 'Xác nhận',
        NoBox: 'Hủy',
        province: 'Tỉnh',
        district: 'Huyện',
        ward: 'Xã',
        dateBirth: 'Chọn ngày sinh',
        yourprovince: "Tỉnh Của Bạn",
        yourdistrict: "Huyện Của Bạn",
        yourward: "Xã Của Bạn",
        women: 'Nữ',
        man: "Nam",
        address: 'Đại chỉ',
        username: 'Họ và tên ',
        home: 'Chọn tòa nhà',
        floor: 'Tầng (ví dụ: 5)',
        rooms: 'Số phòng (ví dụ: 101)',
        updatecardSuccess: 'Cập nhật thành công',
        inputPhonenum: 'Nhập số điện thoại',
        updateCard: 'Cập nhật thông tin thẻ',
        warning: 'Thông báo',
        wasterGroups: 'các nhóm chất thải',
        mgreen_2: 'Doanh nghiệp xã hội uy tín , tin cậy góp phần xây thói quen phân loai rác  và tích điểm, tặng quà cho cư dân trên toàn quốc. Vì văn hoá Việt Nam tốt hơn, Vì môi trường thông minh , xanh- sạch- đẹp.',
        mgreen_3: 'Tầm nhìn',
        mgreen_4: 'Doanh nghiệp xã hội mGreen là cầu nối của cư dân và đối tác ưu đãi để phân loại rác là hành động, thói quen thường lệ trên toàn Việt Nam',
        mgreen_5: 'Giá trị cốt lõi',
        mgreen_6: 'Nhiệt huyết Vì cộng đồng – Trung thực-  Chuyên nghiệp – Uy tín- Hiệu quả- Tinh thần đội nhómHướng dẫn cài thẻ tích điểm phân loại rác mGreen',
        classify: 'Phân loại',
        Collect: 'Thu gom',
        Transport: 'Vận chuyển',
        Handling: 'Xử lý',
        Organic: 'Hữu cơ',
        Recycling: 'Tái chế',
        Rest: 'Còn lại',
        loginMobile: 'Đăng Nhập Bằng Số  Điện thoại',
        Organicwaste: 'Rác hữu cơ',
        text: 'Rác hữu cơ là loại rác dễ phân hủy và có thể  đưa vào tái chế để đưa vào sử dụng cho việc chăm bón và làm thức ăn cho động vật.',
        contentCollect: 'Thu gom riêng vào vật dụng chứa rác để tận dụng làm phân compost (tại gia đình hoặc đưa đến nhà máy xử lý chế biến tập trung thành phân compost).',
        contentTranspot: 'Rác sinh hoạt từ hộ dân, doanh nghiệp, trường học, chợ… được lưu chứa trong các thiết bị lưu chứa chuyển đến các điểm tập kết chuyển lên các xe ép rác chuyên dùng chuyển về các trạm trung chuyển kín sau đó rác được máy ép rác nạp vào các contener kín và được xe chuyên dùng chuyển đổ tại các công trường xử lý rác tập trung của Thành phố. Toàn bộ quá trình thu gom, vận chuyển : rác được chứa trong các thiết bị kín tránh việc rơi vãi và phát tán mùi hôi, nước rác được thu gom, lưu chứa sau đó chuyển đến nhà máy xử lý nước rác',
        Recyclables: 'Rác tái chế',
        inorganic: 'Rác vô cơ',
        like: 'Thích',
        dislike: 'Bỏ thích',
        logout: 'Đăng Xuất ',
        pointPercent: '+điểm ',
        applyTo: 'Áp dụng tới',
        promotion: "Ưu đãi",
        changeGift: 'Đổi quà',
        times: 'Lượt',
        newDeal: "HOT",
        detailPromotion: 'CHI TIẾT ƯU ĐÃI',
        expirationDate: 'Ngày hết hạn :',
        listShoptitle: 'DANH SÁCH CỬA HÀNG',
        myGif: 'Quà của tôi',
        partnerInfotitle: 'Thông tin đối tác',
        titleDetail: 'Thông tin chi tiết',
        noPromotion: 'Chưa có ưu đãi/quà tặng trong mục này !',
        contentHandling: 'Thu gom riêng vào vật dụng chứa rác để tận dụng làm phân compost.',
        texttaiche: 'Rác vô cơ là loxại rác khó phân hủy nhưng có thể đưa vào tái chế để sử dụng nhằm mục đích phục vụ cho con người.',
        textCollect: 'Rác tái chế được tách riêng và đựng trong túi nilon hoặc túi vải để bán lại cho cơ sở tái chế.',
        textHandling: 'Cần được tách riêng, đựng trong túi ny-lon hoặc túi vải để bán lại cho cơ sở tái chế',
        textconlai: 'Rác vô cơ là những loại rác không thể sử dụng được nữa cũng không thể tái chế được mà chỉ có thể xử lý bằng cách mang ra các khu chôn lấp rác thải',
        textCollection: ' Các thành phần rác không có khả năng tái chế sẽ được thu gom, đựng trong dụng cụ chứa rác tại gia đình và đưa đến điểm tập kết để xe chuyên dụng đến vận chuyển đưa đi xử lý tại các khu xử lý rác thải tập trung theo quy định.',
        conlaiHandling: 'Thu gom vào dụng cụ chứa rác và đưa đến điểm tập kết để xe chuyên dụng đến vận chuyển, đưa đi xử lý tại các khu xử lý rác thải tập trung theo quy định.',
        sendVoucher: 'Gửi voucher',
        cancel: 'Hùy bỏ',
        code: 'Mã',
        verify: 'Xác thực',
        loginname: 'Tên đăng nhập',
        password: 'Mật khẩu',
        checkout: 'Đối soát',
        plhInputpassword: 'Mật khẩu của bạn',
        SendVoucherEmail: 'Gửi voucher qua email',
        provinceCode: 'Cung cấp mã ưu tiên cho nhân viên cửa hàng để sử dụng',
        plhInputname: 'Tên đăng nhập của bạn.',
        more: 'xem thêm',
        giftticket: 'Phiếu Nhận Quà',
        stampticket: 'Phiều Tích Tem',
        nav_23: 'ĐỐI TÁC',
        Affiliate: 'Đối tác liên kết',
        nav_24: 'Các hoạt động chính',
        question: 'Câu hỏi thường gặp',
        contact: ' thông tin liên hệ',
        name: 'Tên',
        downloadapp: 'Download App',
        address: 'Địa chỉ',
        lienhe: 'Liên hệ',
        textthugom: 'Để giải quyết vấn đề thu gom rác tái chế và xây dựng thói quen văn minh của người dân, doanh nghiệp xã hội mGreen phối hợp với Trung ương Đoàn Thanh niên cộng sản Hồ Chí Minh triển khai chương trình ứng dụng công nghệ thông tin phục vụ việc phân loại rác tại các hộ gia đình với tên gọi “Hành trình xanh vì môi trường”. Hiện tại , dự án đang triển khai tại 7 tòa tại khu đô thị Dương Nội . Và ngoài ra còn triển khai mô hình “ Văn phòng xanh” tại các khối văn phòng  , tiên phong là Trung Ương Đoàn .',
        textthugom2: 'Nhằm mục đích tang thu nhập cho người lao động nên lực lượng thu gom chủ yếu của mGreen chính là các cô lao công đang làm việt tại các tòa nhà / các văn phòng . Ngoài ra , còn có sự góp mặt của Đoàn Phường, Đoàn Thanh Niên trong công tác tuyên truyền vận động và đi thu gom ',
    },
    en: {
        textthugom2: 'For the purpose of earning income for employees, the main gathering staff of mGreen are the workers working in the buildings / offices. In addition, the presence of the Youth Union, the Youth League in the advocacy and collection',
        textthugom: 'In order to solve the issue of recycling garbage collection and build the civic habits of the people, social enterprises mGreen cooperated with the Central Committee of Ho Chi Minh Communist Youth Union to implement information technology application program The task of classifying garbage in households is called Green Journey for the Environment. Currently, the project is being implemented in 7 courts in Duong Noi urban area. In addition to deploying the "Green Office" model in the office block, pioneered the Central Union.',
        name: 'Name',
        downloadapp: 'Download App',
        address: 'Address',
        lienhe: 'Contact',
        textPLR: 'The society is developing more and more and more and more and more people are living with the environment. Although there are many factories specializing in waste recycling, specialized waste treatment has been very effective but still does not reduce this situation. And it is mostly due to the fact that waste is not properly sorted.So what is called proper classification?.Before being put to treatment, all types of waste generally need to be classified as required.It is recyclable and not recyclable.Non - recyclables include biodegradable organic debris such as leftover food, or broken vegetables, fruit peels, and so on.Recycled items are items that are removed during production or use.They include paper, plastic, iron, steel, plastic bags.Depending on the characteristics of each type, will be separately classified and recycled for various purposes as best suits as possible.The waste sorting process helps reduce the amount of waste in the community that is discharged into the environment as well as economically.It costs a lot to collect, transport and process.Currently, at 2018, the mGreen project only collects recyclables such as paper, plastic, metal, plastic and plastic bags, batteries.In particular, when residents have a battery, they should put in a clean plastic bag or a clean plastic bottle and keep out of reach of children.',
        contact: 'Contact Info',
        question: 'Frequently Asked Questions',
        cooperate: 'Companion',
        Affiliate: 'Affiliate',
        nav_19: 'The birth of mGreen',
        nav_20: 'deployment plan',
        nav_21: 'MISSION VISION',
        nav_22: 'CORE VALUES',
        nav_23: 'PARTNER',
        nav_24: 'Main activities',
        giftticket: 'Gift Ticket',
        stampticket: 'Stamp ticket',
        newDeal: "HOT",
        more: 'more',
        plhInputname: 'Your username',
        loginname: 'Username',
        plhInputpassword: 'Your password',
        password: 'Password',
        checkout: 'Checkout',
        SendVoucherEmail: 'Send voucher via Email',
        sendVoucher: 'Send voucher',
        cancel: 'Cancel',
        code: 'Code',
        verify: 'Verify',
        provinceCode: 'Provide the priority code for the store employee to use',
        titleDetail: 'Details',
        listShoptitle: 'LIST SHOPS',
        partnerInfotitle: 'Partner info',
        detailPromotion: 'DETAIL PROMOTION',
        expirationDate: 'Expiration date :',
        like: 'like',
        times: 'Times',
        dislike: 'Dis like',
        pointPercent: '+point ',
        applyTo: 'Apply to',
        promotion: "promotion",
        changeGift: 'change Gift',
        myGif: 'My Gift',
        noPromotion: 'You have no promotion/gift in this !',
        conlaiHandling: 'Collected into garbage containers and brought to the collection point for special purpose vehicles to be transported and handled at the concentrated waste treatment areas as prescribed.',
        textCollection: 'Non-recyclable garbage will be collected and stored in the household waste collection container and brought to the collection point for the special purpose vehicle to be transported and disposed of at the disposal sites. Medium according to regulations. ',
        textconlai: 'Inorganic waste is a waste that can no longer be used and can not be recycled but can only be treated by bringing it to disposal sites',
        textHandling: 'It should be segregated, stored in a plastic bag or cloth bag for sale to a recycling facility',
        textCollect: 'Recycled waste is segregated and stored in plastic bags or bags for resale.',
        texttaiche: 'Inorganic waste is a difficult to break waste but can be recycled for human consumption.',
        contentHandling: 'Separate into garbage containers for use as compost.',
        inorganic: 'Inorganic waste',
        Recyclables: 'Recyclables',
        contentTranspot: 'Garbage from households, enterprises, schools, markets ... are stored in the storage equipment transferred to the collection points transferred to the specialized garbage trucks to the closed transfer stations then garbage machine squeeze the load into closed containers and be transported by specialized vehicles at the concentrated waste disposal sites of the City. The entire process of collecting and transporting garbage is contained in the sealed equipment to avoid splashing and smelling foul odors, garbage water is collected and stored and then transferred to the waste water treatment plant.',
        contentCollect: 'Separate into garbage containers to make use of compost (at home or to the processing plant focused on compost).',
        text: 'Organic waste is a biodegradable waste that can be recycled for use in animal feeding and animal feeding.',
        Organicwaste: 'Organic waste',
        Rest: 'Rest',
        Recycling: 'Recycling',
        Organic: 'Organic',
        Handling: 'Handling',
        Transport: 'Transport',
        classify: 'Classify',
        Collect: 'Collect',
        loginMobile: 'Login With Phone Number',
        loginGoogle: 'Login With Google',
        floor: 'Floor 5 (example: 5)',
        rooms: 'Number of rooms (example: 101)',
        dateBirth: 'Choose date of birth',
        address: 'Address',
        updatecardSuccess: 'Update success.',
        updateCard: 'Update info',
        logout: 'Log Out',
        home: 'Select a building',
        username: 'First and last name',
        inputPhonenum: 'Phone number',
        women: 'Male',
        man: "Female",
        close: 'Close',
        warning: 'Warning',
        OkBox: 'Ok',
        change: 'Change phone number',
        NoBox: 'Cancel',
        nav_1: 'ABOUT MGREEN',
        nav_2: 'SPONSOR',
        nav_3: 'LOGIN',
        loginFacebook: 'Login With Facebook',
        wasterGroups: 'waste groups',
        nav_4: 'ENDOW',
        nav_5: 'NEW',
        nav_6: 'FEEDBACK',
        nav_7: 'DOWNLOAD APP MGREEN',
        nav_8: 'VIETNAMESE',
        nav_9: 'ENGLISH',
        nav_10: 'LOGIN',
        nav_11: 'SIGNIN',
        nav_12: 'PARTNERS',
        nav_13: 'THE VOLUNTEERS OF THE VOLUNTEERS',
        nav_14: 'mgreen collector',
        nav_15: 'Guidance on waste classification',
        nav_16: 'recycling site',
        nav_17: 'mgreen collector',
        nav_18: 'Collection process',
        slide_1: 'SMART HOUSE',
        slide_2: 'WISE PEOPLE',
        slide_3: 'Point accumulation,',
        slide_4: 'sorting waste mgreen',
        slide_5: 'FREE REGISTRATION FOR MEMBER CARDS',
        slide_6: 'Get discounted million mgreen card',
        slide_7: 'COLLECTION AS SMARTPHONE',
        slide_8: 'Application integrates call collectors and collect points for gift certificates / stamps',
        slide_9: 'SMART CITY TECHNOLOGY',
        slide_10: 'Smart city technology application for sorting garbage.',
        introduce: 'INTRODUCE',
        introduce_1: 'MGreen is a social, non-profit project that aims to build a civilized habit of sorting household waste and protecting the environment.',
        introduce_2: 'The project was directed by the Hanoi People’s Committee and is one of three excellent start-up projects awarded by the Hanoi Information and Communication Department.',
        introduce_3: 'Residents of the project buildings are provided FREE 1 recycling bin and 1 collector card with application to collect collectors. Households classify rubbish, use the application to collect collectors and earn bonus points. Rewards can be exchanged for many valuable gifts.',
        introduce_4: 'YOUR CITY MAKING MORE CONVENIENT AND GREEN - CLEAN - BEAUTIFUL',
        introduce_5: 'YOUR CITY MAKING MORE CONVENIENT AND GREEN - CLEAN - BEAUTIFUL',
        introduce_6: 'DOWNLOAD APP MGREEN',
        introduce_7: 'FIND OUT MORE',
        classify_1: 'Garbage containers',
        classify_2: 'Users will be given a basket of biodegradable waste bags',
        classify_3: 'Giving mGreen card',
        classify_4: 'Users will be given a free mGreen card and also a free mGreen application on their mobile. The mGreen card / app will accumulate bonus points every time you collect garbage',
        classify_5: 'Enjoy the benefits',
        classify_6: 'Users who are redeemed for gift vouchers or coupon stamps from affiliate units affiliated with mGreen',
        classify_7: 'Give away recyclable trash & mgreen card',
        classify_8: 'App notifications are easy to collect',
        classify_9: 'Encouraged: accumulate points, give gifts',
        footer_1: 'Smart City project - mGreen',
        footer_2: '614  Lạc Long Quân - Tây Hồ - Hà Nội',
        footer_3: '0934 68 66 21',
        footer_4: 'thoatran@mgreen.vn',
        footer_5: 'Chat with mGreen',
        province: 'Province',
        district: 'District',
        ward: 'Ward',
        yourprovince: "Your Province",
        yourdistrict: "Your District",
        yourward: "Your Ward",
        introduceatm: 'How to install mGeen card',
        componenttab_1: 'DownLoad App mGreen from AppStore / CH Play',
        componenttab_2: 'Call collectors',
        componenttab_3: 'Confirmation of collection',
        componenttab_4: 'Earn points, redeem, receive incentives',
        mgreen_1: 'Mission',
        mgreen_2: 'Reliable and reliable social enterprise contributes to the habit of distributing rubbish and collecting points, giving gifts to residents across the country. Because Vietnamese culture is better, because the environment is smart, green – clean – beautiful.',
        mgreen_3: 'Vision',
        mgreen_4: 'MGreen social enterprise is a bridge between residents and partners to classify rubbish is the habit, routine routine throughout Vietnam',
        mgreen_5: 'Core values',
        mgreen_6: 'For the community - Honesty- Professional - Prestige - Effectiveness - Team spiritGallery Guide to mark the garbage mGreen',
    }
});

export default strings;